# Config file for the website

[documentation]
text = """
This tool is designed to assist startups in scaling effectively by providing data-driven insights across multiple functional areas. It serves as a twin product to a strategic playbook developed by McKinsey & Company, aimed at guiding startups to prioritize initiatives critical for scaling.

The playbook builds on existing knowledge in the market about scaling up and focuses on three specific lenses:

- The impact of people and organizational structure on a company's ability to scale.
- Insights from Founder recipes of approximately 20 successful Centaur Founders/CEOs.
- A specific focus on B2B SaaS and companies that have undergone hypergrowth.

Through advanced analytics and expert input, including interviews with Founder/CEOs, leveraging public data sources, and engaging with venture capital firms like Pitango Venture Capital, the playbook validates and enhances the strategic direction for growth.
"""

[pillars]
names = [
    "Market and Buyer Discovery", 
    "Path to Product-Market Fit", 
    "Product and Technology", 
    "Go-to-Market Strategy", 
    "SMB Enterprise Segment Analysis",
    "Market and Geographic Expansion",
    "Product Line Expansion",
    "Customer Success Management",
    "Market Demand Generation",
    "Strategic M&A",
    "Ecosystem and Partnerships Development",
    "Talent Excellence and Recruitment",
    "Company Culture Assessment",
    "Planning and Decision-Making Practice Evaluation",
    "Top Team Effectiveness Assessment"
]

[under_construction]
"Market and Buyer Discovery" = true
"Path to Product-Market Fit" = true
"Product and Technology" = true
"Go-to-Market Strategy" = true
"SMB Enterprise Segment Analysis" = true
"Market and Geographic Expansion" = true
"Product Line Expansion" = true
"Customer Success Management" = true
"Market Demand Generation" = true
"Strategic M&A" = true
"Ecosystem and Partnerships Development" =  true
"Talent Excellence and Recruitment" = false
"Company Culture Assessment" = false
"Planning and Decision-Making Practice Evaluation" = true
"Top Team Effectiveness Assessment" = true
