# config.toml is a configuration file that contains the names of the indicators and industries

[startups]
names = ["Startup A", "Startup B", "Startup C"]

[indicators_grouped]
Startup_A = {"growth_rate": "line", "customer_acquisition_cost": "bar"}
Startup_B = {"burn_rate": "line", "lifetime_value": "bar"}
Startup_C = {"employee_growth": "line", "revenue_growth": "bar"}

[shared_indicators]
Indicators = ["Growth Rate", "Burn Rate", "Customer Acquisition Cost", "Lifetime Value", "Employee Growth", "Revenue Growth"]
