# Place this file in the root directory of your Streamlit project

[pillars]
names = [
    "Market / Buyer Discovery", 
    "Path to Product-Market Fit", 
    "Product and Technology", 
    "Go-to-Market Strategy", 
    "SMB / Enterprise Segment Analysis",
    "Market and Geographic Expansion",
    "Product Line Expansion",
    "Customer Success Management",
    "Market Demand Generation",
    "Strategic M&A",
    "Ecosystem and Partnerships Development",
    "Talent Excellence and Recruitment",
    "Company Culture Assessment",
    "Planning and Decision-Making Practice Evaluation",
    "Top Team Effectiveness Assessment"
]

[under_construction]
"Market / Buyer Discovery" = true
"Path to Product-Market Fit" = true
"Product and Technology" = true
"Go-to-Market Strategy" = true
"SMB / Enterprise Segment Analysis" = true
"Market and Geographic Expansion" = true
"Product Line Expansion" = true
"Customer Success Management" = true
"Market Demand Generation" = true
"Strategic M&A" = true
"Ecosystem and Partnerships Development" = true
"Talent Excellence and Recruitment" = true
"Company Culture Assessment" = true
"Planning and Decision-Making Practice Evaluation" = true
"Top Team Effectiveness Assessment" = true
