# Place this file in the root directory of your Streamlit project

[pillars]
names = [
    "Market and Buyer Discovery", 
    "Path to Product-Market Fit", 
    "Product and Technology", 
    "Go-to-Market Strategy", 
    "SMB Enterprise Segment Analysis",
    "Market and Geographic Expansion",
    "Product Line Expansion",
    "Customer Success Management",
    "Market Demand Generation",
    "Strategic M&A",
    "Ecosystem and Partnerships Development",
    "Talent Excellence and Recruitment",
    "Company Culture Assessment",
    "Planning and Decision-Making Practice Evaluation",
    "Top Team Effectiveness Assessment"
]

[under_construction]
"Market and Buyer Discovery" = false
"Path to Product-Market Fit" = false
"Product and Technology" = false
"Go-to-Market Strategy" = false
"SMB Enterprise Segment Analysis" = false
"Market and Geographic Expansion" = false
"Product Line Expansion" = false
"Customer Success Management" = false
"Market Demand Generation" = false
"Strategic M&A" = false
"Ecosystem and Partnerships Development" = false
"Talent Excellence and Recruitment" = false
"Company Culture Assessment" = frue
"Planning and Decision-Making Practice Evaluation" = false
"Top Team Effectiveness Assessment" = false
