# config.toml is a configuration file that contains the names of the indicators and industries

[industries]
names = [
  "Overall_economy",
  "Agriculture",
  "Construction",
  "Manufacturing",
  "Retail",
  "Health_social_sector",
  "Retail_Wholesale",
  "Education",
  "Transportation_and_storage"
]

[indicators_grouped.Overall_economy]
group1 = ["GDP", "FDI inflows", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["Government tax revenue", "Home Price Index", "Consumer confidence index"]
group3 = ["10 year bond yield", "Interest rate", "Level of wages"]
group4 = ["Foreign trade (Import and Export)", "Stock market volatility (VIX)", "CPI (overall, core)"]
group5 = ["PMI Manufacturing", "Loans defaults/Nonperforming loans to total loans", "Personal consumption spending and disposable household income"]
group6 = ["Percentage of Reservists per Industry"]

[indicators_grouped.Agriculture]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["OpEx CAGR of industry leaders", "Companies closed", "Level of wages"]
group3 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group4 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans", "Companies applied for chapter 11"]
group5 = ["Percentage of foreign labor"]

[indicators_grouped.Construction]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["Percentage of foreign labor", "Building Permits Issued", "Level of wages"]
group3 = ["OpEx CAGR of industry leaders", "Companies closed", "Companies applied for chapter 11"]
group4 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group5 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans"]

[indicators_grouped.Manufacturing]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["OpEx CAGR of industry leaders", "Companies closed", "Level of wages"]
group3 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group4 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans", "Companies applied for chapter 11"]
group5 = ["Percentage of foreign labor"]

[indicators_grouped.Retail]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["OpEx CAGR of industry leaders", "Companies closed", "Level of wages"]
group3 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group4 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans", "Companies applied for chapter 11"]
group5 = ["Percentage of foreign labor"]

[indicators_grouped.Health_social_sector]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["OpEx CAGR of industry leaders", "Companies closed", "Level of wages"]
group3 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group4 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans", "Companies applied for chapter 11"]
group5 = ["Percentage of foreign labor"]

[indicators_grouped.Retail_Wholesale]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["OpEx CAGR of industry leaders", "Companies closed", "Level of wages"]
group3 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group4 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans", "Companies applied for chapter 11"]
group5 = ["Percentage of foreign labor"]

[indicators_grouped.Education]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["OpEx CAGR of industry leaders", "Companies closed", "Level of wages"]
group3 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group4 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans", "Companies applied for chapter 11"]
group5 = ["Percentage of foreign labor"]

[indicators_grouped.Transportation_and_storage]
group1 = ["Sales CAGR of industry leaders", "Net working capital and cash reserves as a percentage of turnover", "Real labor participation rate accounting for reserve duty unpaid leave and open vacancies"]
group2 = ["OpEx CAGR of industry leaders", "Companies closed", "Level of wages"]
group3 = ["Foreign trade", "FDI inflows", "Personal consumption spending by category"]
group4 = ["Ability to work remotely", "Loans defaults/Nonperforming loans to total loans", "Companies applied for chapter 11"]
group5 = ["Percentage of foreign labor"]


[industry_specific]
Overall_economy = ["GDP Growth Rate", "Unemployment Rate Trends", "Inflation Rate Changes", "Consumer Spending Patterns", "National Debt Levels", "Foreign Direct Investment Flows", "Currency Strength and Exchange Rates", "Interest Rate Fluctuations", "Economic Policy Impact Assessment", "Business Confidence Survey Results"]
Agriculture = ["Soil Moisture Levels", "Rainfall Averages vs Historical Data", "Temperature Anomalies", "Greeness Index (NDVI)", "Planting and Harvest Dates", "Crop Yield Forecasts and Actuals", "Water Usage Rates", "Agricultural Inputs (Seeds, Fertilizer)", "Commodity Price and Price Volatility", "Export Volumes and Destinations", "Food Stock Levels", "Labor Availability and Costs", "Farm Machinery Sales and Utilization Rates", "Energy Costs for Farming Operations", "Farm Loan Defaults and Support Levels", "Agricultural Subsidies and Support Levels", "Insurance Claim Rates"]
Construction = ["Building Permits Issued", "Construction Output and Volume", "Housing Starts and Completions", "Infrastructure Project Pipelines", "Material Costs Trends", "Construction Equipment Sales", "Labor Force Statistics in Construction", "Construction Loan Interest Rates", "Home Price Index", "Safety Incident Rates and Regulations Compliance", "Default among developers, contractors", "Online announcements of delayed projects", "Construction work visa application", "Level of wages by occupation", "Evacuees housing demand", "Days on market", "Map of Construction Sites"]
Manufacturing = ["Production Output Volume", "Inventory Levels and Turnover Rates", "Manufacturing Employment Rates", "Machine Utilization Rates", "Input Costs", "Product Demand Forecasts", "Export and Import Volumes", "Factory Downtime and Efficiency Metrics", "Supply Chain Disruption Impacts", "Quality Control Metrics", "Raw material delays", "Government support program utilization"]
Retail = ["Consumer Foot Traffic Data", "Sales Volume and Revenue Trends", "Inventory Turnover Rates", "E-commerce Penetration and Growth", "Retail Price Inflation", "Customer Satisfaction and Loyalty Metrics", "Brand Value and Market Share", "Seasonal Sales Performance", "Retail Space Costs", "Omnichannel Retail Adoption Rates"]
Health_social_sector = ["Patient Admission Rates", "Healthcare Workforce Statistics", "Medical Equipment Utilization and Sales", "Healthcare Policy Changes and Impacts", "Public Health Expenditure", "Pharmaceutical Sales and Innovation Rates", "Health Insurance Coverage Rates", "Disease Incidence and Prevalence Rates", "Telemedicine Adoption Trends", "Patient Outcome Statistics"]
Retail_Wholesale = ["Wholesale Sales Volumes", "B2B Customer Satisfaction Indices", "Inventory Carrying Costs", "Wholesale Market Price Trends", "Retailer Demand Forecasts", "Distribution Network Efficiency", "Vendor Management Effectiveness", "Credit Terms and Payment Periods", "Return Rates and Processing Costs", "Trade Promotion Effectiveness"]
Education = ["Student Enrollment and Graduation Rates", "Education Funding Levels", "Teacher to Student Ratios", "Academic Performance Metrics", "Technology Adoption in Classrooms", "Education Infrastructure Investments", "Special Education Program Availability", "School Operation Costs", "Workforce Skills Gap Analysis", "Online Education Engagement Rates"]
Transportation_and_storage = ["Freight Volumes and Transport Efficiency", "Logistics Costs Trends", "Fuel Price Fluctuations and Impact", "Transportation Infrastructure Development", "Vehicle Fleet Age and Maintenance Costs", "Warehouse Space Availability and Utilization", "Carrier Performance Metrics", "Regulatory Changes Affecting Transportation", "Transportation Safety and Accident Rates", "Digitalization of Supply Chain Operations"]

[shared_indicators]
Indicators = ["Economic Growth Rate", "Unemployment Rate", "Inflation Rate", "Interest Rates", "Consumer Confidence", "Exchange Rates"]


[indicator_plot_types]
"GDP" = "line"
"FDI inflows" = "bar"
"Real labor participation rate accounting for reserve duty unpaid leave and open vacancies" = "scatter"
"10 year bond yield" = "line"
"Interest rate" = "area"
"Level of wages" = "line"
"Foreign trade (Import and Export)" = "bar"
"Stock market volatility (VIX)" = "scatter"
"CPI (overall, core)" = "area"
"PMI Manufacturing" = "line"
"Loans defaults/Nonperforming loans to total loans" = "bar"
"Personal consumption spending and disposable household income" = "scatter"
"Personal consumption spending by category" = "bar"
"Government tax revenue" = "line"
"Home Price Index" = "area"
"Consumer confidence index" = "line"
"Sales CAGR of industry leaders" = "bar"
"Net working capital and cash reserves as a percentage of turnover" = "scatter"
"OpEx CAGR of industry leaders" = "line"
"Companies closed" = "bar"
"Foreign trade" = "line"
"Ability to work remotely" = "scatter"
"Raw material delays" = "area"
"Government support program utilization" = "line"
"Companies applied for chapter 11" = "line"
"Percentage of foreign labor" = "area"
"Percentage of Reservists per Industry" = "..."

# Shared indicators
"Economic Growth Rate" = "line"
"Unemployment Rate" = "bar"
"Inflation Rate" = "area"
"Interest Rates" = "line"
"Consumer Confidence" = "scatter"
"Exchange Rates" = "line"

# Unique indicators for Overall_economy
"GDP Growth Rate" = "line"
"Unemployment Rate Trends" = "bar"
"Inflation Rate Changes" = "area"
"Consumer Spending Patterns" = "scatter"
"Foreign Direct Investment Flows" = "line"
"Currency Strength and Exchange Rates" = "bar"
"Interest Rate Fluctuations" = "line"
"Economic Policy Impact Assessment" = "scatter"
"National Debt Levels" = "area"
"Business Confidence Survey Results" = "line"

# Unique indicators for Agriculture
"Soil Moisture Levels" = "scatter"
"Rainfall Averages vs Historical Data" = "bar"
"Temperature Anomalies" = "line"
"Greeness Index (NDVI)" = "area"
"Planting and Harvest Dates" = "scatter"
"Crop Yield Forecasts and Actuals" = "bar"
"Water Usage Rates" = "line"
"Agricultural Inputs (Seeds, Fertilizer)" = "scatter"
"Commodity Price and Price Volatility" = "area"
"Export Volumes and Destinations" = "line"
"Food Stock Levels" = "scatter"
"Labor Availability and Costs" = "bar"
"Farm Machinery Sales and Utilization Rates" = "line"
"Energy Costs for Farming Operations" = "scatter"
"Farm Loan Defaults and Support Levels" = "area"
"Agricultural Subsidies and Support Levels" = "line"
"Insurance Claim Rates" = "bar"

# Unique indicators for Construction
"Building Permits Issued" = "bar"
"Construction Output and Volume" = "line"
"Housing Starts and Completions" = "area"
"Infrastructure Project Pipelines" = "scatter"
"Material Costs Trends" = "line"
"Construction Equipment Sales" = "bar"
"Labor Force Statistics in Construction" = "scatter"
"Construction Loan Interest Rates" = "line"
"Safety Incident Rates and Regulations Compliance" = "bar"
"Default among developers, contractors" = "bar"
"Online announcements of delayed projects" = "line"
"Construction work visa application" = "scatter"
"Level of wages by occupation" = "area"
"Evacuees housing demand" = "line"
"Days on market" = "scatter"

# Unique indicators for Manufacturing
"Production Output Volume" = "line"
"Inventory Levels and Turnover Rates" = "area"
"Manufacturing Employment Rates" = "scatter"
"Machine Utilization Rates" = "line"
"Input Costs" = "bar"
"Product Demand Forecasts" = "scatter"
"Export and Import Volumes" = "line"
"Factory Downtime and Efficiency Metrics" = "bar"
"Supply Chain Disruption Impacts" = "scatter"
"Quality Control Metrics" = "area"

# Unique indicators for Retail
"Consumer Foot Traffic Data" = "scatter"
"Sales Volume and Revenue Trends" = "line"
"Inventory Turnover Rates" = "bar"
"E-commerce Penetration and Growth" = "area"
"Retail Price Inflation" = "scatter"
"Customer Satisfaction and Loyalty Metrics" = "line"
"Brand Value and Market Share" = "area"
"Seasonal Sales Performance" = "bar"
"Retail Space Costs" = "scatter"
"Omnichannel Retail Adoption Rates" = "line"

# Unique indicators for Health and Social Sector
"Patient Admission Rates" = "bar"
"Healthcare Workforce Statistics" = "line"
"Medical Equipment Utilization and Sales" = "scatter"
"Healthcare Policy Changes and Impacts" = "area"
"Public Health Expenditure" = "line"
"Pharmaceutical Sales and Innovation Rates" = "bar"
"Health Insurance Coverage Rates" = "scatter"
"Disease Incidence and Prevalence Rates" = "line"
"Telemedicine Adoption Trends" = "area"
"Patient Outcome Statistics" = "scatter"

# Unique indicators for Retail_Wholesale
"Wholesale Sales Volumes" = "line"
"B2B Customer Satisfaction Indices" = "scatter"
"Inventory Carrying Costs" = "bar"
"Wholesale Market Price Trends" = "line"
"Retailer Demand Forecasts" = "scatter"
"Distribution Network Efficiency" = "area"
"Vendor Management Effectiveness" = "scatter"
"Credit Terms and Payment Periods" = "bar"
"Return Rates and Processing Costs" = "line"
"Trade Promotion Effectiveness" = "scatter"

# Unique indicators for Education
"Student Enrollment and Graduation Rates" = "bar"
"Education Funding Levels" = "line"
"Teacher to Student Ratios" = "scatter"
"Academic Performance Metrics" = "area"
"Technology Adoption in Classrooms" = "line"
"Education Infrastructure Investments" = "scatter"
"Special Education Program Availability" = "bar"
"School Operation Costs" = "line"
"Workforce Skills Gap Analysis" = "scatter"
"Online Education Engagement Rates" = "area"

# Unique indicators for Transportation and Storage
"Freight Volumes and Transport Efficiency" = "line"
"Logistics Costs Trends" = "bar"
"Fuel Price Fluctuations and Impact" = "scatter"
"Transportation Infrastructure Development" = "area"
"Vehicle Fleet Age and Maintenance Costs" = "scatter"
"Warehouse Space Availability and Utilization" = "line"
"Carrier Performance Metrics" = "bar"
"Regulatory Changes Affecting Transportation" = "scatter"
"Transportation Safety and Accident Rates" = "line"
"Digitalization of Supply Chain Operations" = "area"
